<?php
echo $this->methodblock();
?>
<br/>
<br/>
<form action="<?php echo Mage::getUrl('test/index/save') ?>" method="post">
    <fieldset>
        <ul>
            <li>
                <label for="nom">Nomer</label>
                <input type="text" id="nom" name="nom" />
            </li>
            <li>
                <label for="prenom">Text</label>
                <input type="text" id="prenom" name="prenom" />
            </li>
            <li>
                <label for="nom">Telephone</label>
                <input type="text" id="telephone" name="telephone" />
            </li>
            <li>
                <input type="submit" value="Save" />
            </li>
        </ul>
    </fieldset>

</form>
